//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class TangoStruct
		{
		public float timestamp { get; set; }
		public int xyz_count { get; set; }
		public char[] xyz_parcel { get; set; }
			public TangoStruct(float ts, int xyzc, char[] xyzp)
			{
				timestamp = ts;
				xyz_count = xyzc;
				xyz_parcel = xyzp;
			}
		}
}

